codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5

flag_management:
  default_rules:
    carryforward: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
