[pytest]
addopts =
    --durations-min=30.0
    --durations=0
    --ignore-glob=sub-packages/bionemo-moco/examples/discrete_data_interpolant_tutorial.ipynb
markers =
    slow: medium-complexity tests, like integration tests, on a single GPU
    multi_gpu: tests that require multiple GPUs
    distributed: tests that require distributed setup via torchrun execution
